# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
    region = "eu-central-1"

    # default tags
    default_tags {
        tags = {
            Environment     = "dev"
            ManagedBy       = "pawel.polski99@gmail.com"
            Project         = "STEP-FUNCTIONS"
            TaggingVersion  = "v2.4"
            Confidentiality = "C3"
        }
    }
}
